spring.application.name=api-gateway
server.port=8080


spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=http://order-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=http://inventory-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory/**